stages:
  - build
  - release # New stage

build:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-pdf-cache # Unique cache key per branch
    paths:
      - 'Html/*.html'
      - 'R/EData.RData'
      - 'R/Z23_morlet.RData'
      - 'Png/*.png'
      - 'R/*.png'
    policy: pull-push # Default behavior: pull the cache before script, push after script
  variables:
    GIT_SUBMODULE_STRATEGY: recursive  # Or 'normal' if you don't have nested submodules
  script:
    - git submodule update
    - echo `ls templates`
    - make presentation
    - make html
    - echo "JOB_ID=$CI_JOB_ID" > artifacts_vars.env 
  artifacts:
    paths:
       - Pdf_output/2025_Coldigiocco_presentation.pdf
       - Html/beatings.html
       - Html/finding_eccentricity_frequenties.html
       - Html/ob_vs_ecc_beatings.html
       - Html/insolation.html
       - artifacts_vars.env
    reports:
      dotenv: artifacts_vars.env # NEW: Make variables available to subsequent jobs
    expire_in: 1 week
  only:
    - master
  when: manual

release:
  stage: release
  needs:
    - job: build
  script:
    - export CI_COMMIT_TAG="build-${CI_COMMIT_SHORT_SHA}"
    - export BASE_URL="${CI_PROJECT_URL}/-/jobs/${JOB_ID}/artifacts/file"
    - ASSETS_JSON='[
        {"name":"Presentation PDF","url":"'$BASE_URL'/Pdf_output/2025_Coldigiocco_presentation.pdf?job=build"},
        {"name":"Beatings html","url":"'$BASE_URL'/Html/beatings.html?job=build"},
        {"name":"Insolation html","url":"'$BASE_URL'/Html/ob_vs_ecc_beatings.html?job=build"}, 
        {"name":"Finding ecc frequencies html","url":"'$BASE_URL'/Html/finding_eccentricity_frequenties.html?job=build"} ]'
    - |
      glab release create "${CI_COMMIT_TAG}" \
           --name "Release ${CI_COMMIT_TAG} with ${CI_COMMIT_SHORT_SHA}" \
           --notes "Automated build from commit ${CI_COMMIT_SHA}" \
           --assets-links "${ASSETS_JSON}" \
  when: manual # Make this manual to control when a release is made

